/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiChatSessionRouteImport } from './routes/api.chat-session'
import { Route as ApiInquiriesRouteImport } from './routes/api.inquiries'
import { Route as ApiInquiryDraftsRouteImport } from './routes/api.inquiry-drafts'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSessionRoute = ApiChatSessionRouteImport.update({
  id: '/api/chat-session',
  path: '/api/chat-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiriesRoute = ApiInquiriesRouteImport.update({
  id: '/api/inquiries',
  path: '/api/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiryDraftsRoute = ApiInquiryDraftsRouteImport.update({
  id: '/api/inquiry-drafts',
  path: '/api/inquiry-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-session': typeof ApiChatSessionRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry-drafts': typeof ApiInquiryDraftsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-session': typeof ApiChatSessionRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry-drafts': typeof ApiInquiryDraftsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-session': typeof ApiChatSessionRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/api/inquiry-drafts': typeof ApiInquiryDraftsRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-session'
    | '/api/inquiries'
    | '/api/inquiry-drafts'
    | '/work/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-session'
    | '/api/inquiries'
    | '/api/inquiry-drafts'
    | '/work/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-session'
    | '/api/inquiries'
    | '/api/inquiry-drafts'
    | '/work/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatSessionRoute: typeof ApiChatSessionRoute
  ApiInquiriesRoute: typeof ApiInquiriesRoute
  ApiInquiryDraftsRoute: typeof ApiInquiryDraftsRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-session': {
      id: '/api/chat-session'
      path: '/api/chat-session'
      fullPath: '/api/chat-session'
      preLoaderRoute: typeof ApiChatSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiries': {
      id: '/api/inquiries'
      path: '/api/inquiries'
      fullPath: '/api/inquiries'
      preLoaderRoute: typeof ApiInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiry-drafts': {
      id: '/api/inquiry-drafts'
      path: '/api/inquiry-drafts'
      fullPath: '/api/inquiry-drafts'
      preLoaderRoute: typeof ApiInquiryDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatSessionRoute: ApiChatSessionRoute,
  ApiInquiriesRoute: ApiInquiriesRoute,
  ApiInquiryDraftsRoute: ApiInquiryDraftsRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
